apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
      version: green
  template:
    metadata:
      labels:
        app: flaskapp
        version: green
    spec:
      containers:
        - name: flaskapp
          image: saicharan12121/flaskapp:v2
          ports:
            - containerPort: 5000
