apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-<+deployment.identifier>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
      version: <+deployment.identifier>
  template:
    metadata:
      labels:
        app: flaskapp
        version: <+deployment.identifier>
    spec:
      containers:
        - name: flaskapp
          image: <+artifact.image>
          ports:
            - containerPort: 5000
