apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-<+deployment.identifier>    # auto becomes flaskapp-blue or flaskapp-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
      version: <+deployment.identifier>
  template:
    metadata:
      labels:
        app: flaskapp
        version: <+deployment.identifier>
    spec:
      containers:
        - name: flaskapp
          image: <+artifact.image>           # image: saicharan12121/flaskapp:v1 or v2
          ports:
            - containerPort: 5000
