apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  type: LoadBalancer
  selector:
    app: flaskapp
    version: <+infra.activeService.name>    # either blue or green, Harness controls this
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
