apiVersion: v1
kind: Service
metadata:
  name: flask-service
  annotations:
    harness.io/direct-apply: "true"
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: flask
    version: blue  # Harness will patch this selector to switch traffic
