apiVersion: v1
kind: Service
metadata:
  name: flask-service-stage
  annotations:
    harness.io/direct-apply: "true"
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: flask
    harness.io/color: green
    version: green
