apiVersion: v1
kind: Service
metadata:
  name: flask-service
  annotations:
    harness.io/primary-service: "true"   # <--- REQUIRED for Harness to work
    harness.io/direct-apply: "true"      # Optional but good to keep
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: flask
    version: blue
    harness.io/color: blue
